# ----
# Site

title: Angular 2 Testing Quickstart
description: A simple guide to unit testing in Angular 2
url: https://angular2-testing-quickstart.com
google_analytics_key:
permalink: pretty
baseurl: /angular2-testing-quickstart

collections:
  components:
    title: Components
    position: 1
  isolated:
    title: Isolated
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
